name: IslandKiss
favicon: null
layout_spectrum: 0.96964
typography_spectrum: 0
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#2b2a28'
    - '#175890'
    - '#787677'
    - '#b2b4b3'
  brandStrength: 0.125
  lightness: 0.9629624993540347
  saturation: 0.5496079141739756
  rhythmicContrast: 0.6792796300724149
purpose: []
